name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y lcov

    - name: Configure
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Debug ..

    - name: Build
      run: |
        cd build
        cmake --build .

    - name: Test
      run: |
        cd build
        ctest --output-on-failure

    - name: Generate coverage report
      run: |
        cd build
        make coverage

    - name: Check coverage.info exists
      run: |
        cd build/tests
        if [ ! -f coverage.info ]; then
          echo "Error: coverage.info was not generated. Please check the coverage report generation step."
          exit 1
        fi

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: build/tests/coverage_report
        retention-days: 5

    - name: Calculate coverage percentage
      id: coverage
      run: |
        cd build/tests
        echo "Raw lcov summary:"
        lcov --summary coverage.info
        echo "Extracting coverage percentage..."
        COV=$(lcov --summary coverage.info | grep "lines......:" | awk '{print $2}' | tr -d '%')
        echo "Extracted coverage: $COV"
        if [ -z "$COV" ]; then
          echo "Error: Could not extract coverage percentage"
          exit 1
        fi
        echo "coverage=$COV" >> $GITHUB_OUTPUT

    - name: Update coverage badge
      run: |
        echo "Using coverage value: ${{ steps.coverage.outputs.coverage }}"
        mkdir -p badges
        curl -o badges/coverage.svg "https://img.shields.io/badge/coverage-${{ steps.coverage.outputs.coverage }}%25-brightgreen"
        echo "Badge generated. Current git status:"
        git status
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add badges/coverage.svg
        if [ -n "$(git status --porcelain)" ]; then
          echo "Changes detected, committing..."
          git commit -m "Update coverage badge to ${{ steps.coverage.outputs.coverage }}%"
          git push
        else
          echo "No changes to commit"
        fi
